version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package.json" }}
    paths:
      - ~/open-rpc-near-token-standards/node_modules

  # -------------------------
  #  ALIASES: Branch Filters
  # -------------------------
  - &filter-only-master
    branches:
      only: main
  - &filter-only-semantic-pr
    branches:
      only:  /^(pull|fix|feat|dependabot)\/.*$/

defaults: &defaults
  working_directory: ~/open-rpc-near-token-standards

jobs:

  build:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - run: npm run test --workspaces --if-present
      - save_cache: *save-deps-cache

  release-simple-nft:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release --ignore-packages=packages/simple-ft/**,packages/ft-standard/**,packages/nft-standard/**,packages/standards-specs/**
      
  release-nft-standard:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release --ignore-packages=packages/simple-ft/**,packages/ft-standard/**.packages/simple-nft/**,packages/standards-specs/**

  release-simple-ft:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release --ignore-packages=packages/simple-nft/**,packages/nft-standard/**,packages/ft-standard/**,packages/standards-specs/**

  release-ft-standard:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release --ignore-packages=packages/simple-nft/**,packages/nft-standard/**,packages/simple-ft/**,packages/standards-specs/**

  release-specs:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release --ignore-packages=packages/simple-**/**,packages/nft-**/**,packages/ft-**/**


  release:
    <<: *defaults
    docker:
      - image: circleci/node:15.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm install multi-semantic-release semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin @open-rpc/semantic-release-plugin
      - run: ./node_modules/.bin/multi-semantic-release

workflows:
  version: 2
  analysis:
    jobs:
      - build:
          filters: *filter-only-semantic-pr

  release-simple-ft:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build 
      - release-simple-ft:
          filters: *filter-only-master
          requires:
            - hold

  release-ft-standard:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build 
      - release-ft-standard:
          filters: *filter-only-master
          requires:
            - hold

  release-simple-nft:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build 
      - release-simple-nft:
          filters: *filter-only-master
          requires:
            - hold

  release-nft-standard:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build 
      - release-nft-standard:
          filters: *filter-only-master
          requires:
            - hold
  release-specs:
    jobs:
      - build:
          filters: *filter-only-master
      - hold:
          filters: *filter-only-master
          type: approval
          requires:
            - build 
      - release-nft-standard:
          filters: *filter-only-master
          requires:
            - hold